name: ui
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  time_range_picker: any

  # This is used for the map
  flutter_map: ^0.12.0

  # Used to cluster the markers on the map
  flutter_map_marker_cluster: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/kid.png
    - assets/anime.png
    - assets/business.png
    - assets/clean.png
    - assets/arthas.png
    - assets/wolf.png
    - assets/MapTogether_popUp.png

  module:
    androidX: true
    androidPackage: maptogether.client.ui
    iosBundleIdentifier: maptogether.client.ui
