name: maptogether_api
description: A library for accessing the maptogether api
version: 1.0.0
homepage: https://github.com/SEbbaDK/p8

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies: 
  http: ^0.13.3
