# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
flutter_application_path = '../ui'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios
  install_all_flutter_pods(flutter_application_path)

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
	install_all_flutter_pods(flutter_application_path)
  end

  target 'iosUITests' do
    # Pods for testing
	install_all_flutter_pods(flutter_application_path)
  end

end
