name: "server"

on:
  push:
    paths:
      - "server/**"
      - .github/workflows/server.yml
  pull_request:
    paths:
      - "server/**"
      - .github/workflows/server.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v5
      - run: nix-shell server --quiet --run "cd server && ./test.sh"
